#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
  CREATE USER autocotizador WITH PASSWORD '$AUTOCOTIZADOR_DB_PASSWORD' CREATEDB;
  CREATE USER brica_stockintermedio WITH PASSWORD '$BRICA_STOCKINTERMEDIO_DB_PASSWORD' CREATEDB;
  CREATE USER sumin_stockintermedio WITH PASSWORD '$SUMIN_STOCKINTERMEDIO_DB_PASSWORD' CREATEDB;
EOSQL
